- hosts: all
  vars_files:
   vars.yml

  tasks: 
  - name: "Installing HTTPD"
    package:
     name: "httpd"
     state: present

  - name: "Starting HTTPD Service"
    service:
     name: "httpd"
     state: started

  - name: "Copying Configuration File"
    template:
     src: "webconf.conf"
     dest: "/etc/httpd/conf.d/webconf.conf" 
    notify: Restart WebServer
    
  - name: "Enabling Firewall"
    firewalld:
     port: "{{port_no}}/tcp"
     state: enabled
     permanent: yes
     immediate: yes

  - name: "New Document Root Directory"
    file:
     state: directory
     path: "{{ document_root }}"

  - name: "Copying Content to WEB Server"
    copy:
     content: " WEB Server Successfully Configured"
     dest: "{{document_root}}/index.html"

  handlers:
  - name: "Restart WebServer"
    service:
     name: "httpd"
     state: restarted
